rstudio/pins-r

- .travis.yml
- DESCRIPTION
- NEWS.md
- R/board_github.R
- R/pin.R
- R/pin_download.R
- man/pin_find.Rd
- tests/testthat/test-board-github.R
GitHub only allows 100MB files to be uploaded as content, the API takes a `base64` encoded file which makes it even lower than  100MB. This PR adds support to store files larger than 50MB (due to encoding overhead) to be store as GitHub release files. See [Distributing large binaries](https://help.github.com/en/articles/distributing-large-binaries).
> Support GitHub release files

- NEWS.md
- R/board_datatxt.R
The GitHub board might create GitHub releases to store large files (as recommended by GitHub); however, boards that only register the `data.txt` YAML file currently can't download those large GitHub files, and in general, any URL reference stored in the pin manifest.
> Follow up fix for GitHub Releases feature

- R/pin_file.R
When searching for resources in the UI viewer, the extension might be missing in file-based pins.
> Properly store file ext in metadata

- NEWS.md
- R/board.R
- R/board_packages.R
- R/board_registry.R
- R/board_rsconnect.R
- R/pin.R
- man/board_default.Rd
- man/pin.Rd
- man/pin_get.Rd
- man/pin_remove.Rd
- tests/testthat/helper-initialize.R
- tests/testthat/test-aaa-check.R
- tests/testthat/test-zzz-check.R
- vignettes/boards-understanding.Rmd
- vignettes/pins-starting.Rmd
This PR replaces the default `temp` board with the `local` board, which is more appropriate to share data across R sessions and can now be enabled by default since the cache being used is defined by `rappdirs::user_cache_dir()`, which many other R packages already use.
> Register local board by default

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_token.R
From @slopp,
```
library(pins)
board_register("rsconnect", server = "https://colorado.rstudio.com/rsc")
pin_get("alex.gold/bike_rental_stations", board = "rsconnect")
```
Two issues,
1) RStudio Connect boards with subpaths `rsc` are not properly working, other servers work buy there might be redirects in place.
2) Not correctly searching for pins across all users when attempting to retrieve a pin by name.
> Support subpaths and shred pins in RStudio Connect

- NEWS.md
- R/board_github.R
Still hitting "server error" error in the GitHub API while uploading 47mb files, so scoping uploads to 25mb and release files after 25mb.
> Adjust down max github upload size avoid server error

- NEWS.md
- R/board_github.R
- R/board_registration.R
- vignettes/boards-github.Rmd
Fix for https://github.com/rstudio/pins/issues/63,
```r
board_register_github(repo = "javierluraschi/foo")
```
triggers,
```
Error in board_initialize.github(board, ...) : 
The repo 'javierluraschi/foo' does not exist or can't be accessed: Not Found 
```
and updates docs.
> Trigger error when GitHub repo is missing

- NEWS.md
- R/board_rsconnect.R
- R/board_test.R
- R/pin.R
- R/ui_viewer.R
- man/pin_find.Rd
In RStudio Connect boards when pins have similar names, for example `iris` and `iris-lm`, both where being retrieved by internal APIs and the pin not properly removed. Fix on its way.
> Fix to `pin_remove()` for pins with similar names in RSC boards

- NEWS.md
- R/board.R
Fix for https://github.com/rstudio/pins/issues/67. Code should generate `board_register_local()` or `board_register(name = "rsconnect")`.
> Fix generated connection code for auto boards

- NEWS.md
- R/pin_extensions.R
Reprex:
```
model_base <- "https://storage.googleapis.com/gpt-2/models/124M/"
model_files <- c("checkpoint", "encoder.json", "hparams.json", "model.ckpt.data-00000-of-00001", "model.ckpt.index", "model.ckpt.meta", "vocab.bpe")
model_urls <- paste0(model_base, model_files)
pins::pin(model_urls)
```
```
Error in dir.create(path, recursive = TRUE) : invalid 'path' argument
```
> support auto-names with character vectors in pin()

- NEWS.md
- R/board_rsconnect.R
Some RStudio Connect servers retrieve content entries as:
```
"https://colorado.rstudio.com/rsc/bike_available_model/"
```
While others as
```
"https://beta.rstudioconnect.com/content/6476/"
```
This fix accounts for both of them.
> Fix for rsc servers where /content/ not in the url

- DESCRIPTION
- R/board_datatxt.R
Currently we're assuming paths given in the `data.txt` for a datatxt board are relative so we prepend the board URL to download paths. With this PR we check first to see if a proper URL (http/https) is given.
> Support absolute paths for datatxt boards

- vignettes/boards-azure.Rmd
Fixing up docs, looks like you adapted the Kaggle vignette for Azure. Found two cases where Kaggle was referred to, switched them to Azure.
> Switch from Kaggle -> Azure for azure documentation

- R/board_registration.R
When testing `pins::board_register_azure()` it seems the wrapper wasn't passing the account string through. I think this proposed PR will fix that (untested).
Example of what is/isn't working for me:
> Pass through account to wrapper for Azure

- NEWS.md
- R/board_rsconnect.R
RStudio Connect pins where being stored as:
```
/cache
/rsconnect
/mtcars
/data.csv
/data.rds
/jluraschi
/mtcars
/data.txt
```
we should download all files in the user folder to support downloading pins with same name from different users.
> Store all files under user folder for rsconnect board

- DESCRIPTION
- NEWS.md
- R/board_github.R
Fix for https://github.com/rstudio/pins/issues/119, fixing `pin_find()`, `pin_remove()` and `pin()` when overriding pins.
> Fix GitHub subpaths issues

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_api.R
Previous versions of RSC did not supported `pins` so we were not using the `pins` content type while searching, this is now supported and unblocks cases where pins are not retrieved due to many results that are not pins.
> Ensure pin_find() retrieves all pins in RStudio Connect

- NEWS.md
- R/board.R
- R/pin.R
`pin_find()` was causing some boards to register with `board_get()` in the connections pane. Fixes https://github.com/rstudio/pins/issues/137.
> Suggest correct registration code in RStudio connections pane

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Fix for https://github.com/rstudio/pins/issues/149
> Properly expose error messages when pin fails to create in rsconnect

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- tests/testthat/test-board-rsconnect.R
It has been reported problems when a board is registered with trailing slashes, the `pins` codebase assumes no trailing slash, so this fix simply removes the trail when a board is registered and runs all tests with and without registering using a trailing slash.
> Properly support registering rsconnect with trails

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Create 70mb file,
```r
saveRDS(matrix(rnorm(10 * 10^6), ncol = 10), "size-70mb.rds")
```
Uploading this file as a pin causes error due to typo in `pins 0.3.0` release,
```r
pin("size-70mb.rds", "size-70mb", board = "rsconnect")
```
```
Error in curl::form_file(path, type) : is.character(type) is not TRUE
```
> Fix large uploads when using rsconnect board

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
A pin in rsconnect boards might fail to create a preview, we should not fail the entire operation but rather create the default assets and warn of the problem.
> Gracefully handle errors when a pin's preview can't be created in rsconnect

- python/pins/__init__.py
- tests/testthat/test-board-packages.R
Python / Jupyer code:
```python
pip install git+https://github.com/rstudio/pins.git@bugfix/python-install#subdirectory=python
import pins
pins.pin_get("hpiR/seattle_sales")
import pandas as pd
import numpy as np
data = np.array([['','Col1','Col2'],
['Row1',1,2],
['Row2',3,4]])
data = pd.DataFrame(data=data[1:,1:], index=data[1:,0], columns=data[0,1:])
data
pins.board_register("rsconnect", server = "https://connect.rstudioservices.com",
key = "APIKEY")
pins.pin(data, "jupyter-test", board = "rsconnect")
```
> Support installing pins from Jupyter

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- R/pin.R
- man/pin_info.Rd
- tests/testthat/test-pin-info.R
Fix for https://github.com/rstudio/pins/issues/160, adds support for `metadata = FALSE` in `pin_info()` to avoid attempting to retrieve pin's content. This can be useful when admins are using `pin_info()` to understand a pin they don't have access to.
This feature can be installed as follows:
```r
remotes::install_github("rstudio/pins", ref = "bugfix/pin-info-metadata")
```
> Support for metadata in pin_info()

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Currently,
```r
pin_get("iris", board = "rsconnect")
```
```
Error in board_pin_get.rsconnect(board_get(board), name, extract = extract,  : 
The pin 'iris' is not available in the 'rsconnect' board. 
```
This PR,
```r
pin_get("iris", board = "rsconnect")
```
```
Error in rsconnect_get_by_name(board, name) : 
Multiple pins named 'iris' in board 'rsconnect', choose from: 'cole/iris', 'nathan/iris', 'mark/iris'. 
```
> Improve error message in rsconnect boards with dupe names to fix #171

- DESCRIPTION
- NEWS.md
- R/board_github.R
- R/board_registration.R
- man/board_register_github.Rd
Attempt to support GitHub Enterprise by registering GitHub as:
```r
library(pins)
board_register_github(repo = "owner/repo", host = "https://yourhostname/api/v3")
```
GitHub Enterprise docs: https://developer.github.com/enterprise/2.17/v3/#authentication
> Support for GitHub Enterprise

- DESCRIPTION
- NEWS.md
- R/board_local.R
- R/pin_registry.R
- tests/testthat/test-pin-object.R
Users have reported that in automated scripts the cache index can get corrupted.
> Support concurrent pin() with shared cache

- NEWS.md
- R/board_test.R
- R/pin_extensions.R
When calling,
```
system.time(pin("http://www.fhfa.gov/datatools/downloads/documents/hpi/hpi_master.csv"))
```
this was slowed down since public pins (like rsconnect) now check to download the pin manifest which introduces lag, this can be mitigated by ignoring this manifest when a specific file is requested.
> Fix performance regression introduced by rsconnect public downloads

- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_bundle.R
- inst/views/data/index.html
Fix for https://github.com/rstudio/pins/issues/77, as in:
```
pin(iris, board = "rsconnect", pin_code = 'pin_get("abc")')
```
to generate:
> Add support to customize pin code to fix #77

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
This change
- Allows the setting of access type of pins on RStudio Connect. Currently, users must log in to RStudio Connect and change access type through the GUI.
Tested manually with
```
library(pins)
board_register("rsconnect",
server = "https://colorado.rstudio.com/rsc",
key = Sys.getenv("CONNECT_API_KEY"))
pin(iris, "iris_private", board = "rsconnect")
pin(iris, "iris_public", board = "rsconnect", access_type = "all")
```
> allow setting of `access_type` for rsconnect

- DESCRIPTION
- NEWS.md
- R/pin_download.R
The following code was not properly updating the cache due to server returning `NULL` etags:
```
usa <- readr::read_csv(pins::pin("http://covidtracking.com/api/states/daily.csv", name = "covid-usa"))
```
> Update pin cache when etag is null

- DESCRIPTION
- NEWS.md
- R/pin.R
- R/pin_extensions.R
- R/pins_metadata.R
- R/ui_viewer.R
- tests/testthat/test-pin-metadata.R
- tests/testthat/test-pins-metadata.R
Support for,
```r
pin(iris, "iris-metadata", custom_metadata = list(
source = "The R programming language",
columns = list(
list(name = "Species", description = "Really like this column"),
list(name = "Sepal.Length", description = "Sepal Length"),
list(name = "Sepal.Width", description = "Sepal Width"),
list(name = "Petal.Length", description = "Petal Length"),
list(name = "Petal.Width", description = "Petal Width"))
)
)
pin_info("iris-metadata", board = "local", metadata = TRUE, extended = TRUE) %>%
yaml::as.yaml() %>%
cat()
```
```
name: iris-metadata
description: ''
type: table
path:
- iris-metadata/data.csv
- iris-metadata/data.rds
rows: 150
cols: 5
source: The R programming language
columns:
- name: Sepal.Length
type: numeric
description: Sepal Length
- name: Sepal.Width
type: …
```
> Add support for custom_metadata for advanced use cases

- DESCRIPTION
- NEWS.md
- R/board_registration.R
Production environments usually set the `R_CONFIG_ACTIVE` environment variable by using the `config` package. Avoid using caches in those environments unless requested explicitly by setting a `PINS_USE_CACHE` environment variable.
> Disable caches when running inside RStudio Connect and other prod environments

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
If uploads fail in RStudio Connect, it can be possible to end up with a pin with missing `data.txt` metadata. This fix allows re-uploading the pin in such case.
> Support recreating pin with corrupt metadata in RStudio Connect

- DESCRIPTION
- NEWS.md
- R/pin_download.R
- R/pin_extensions.R
For large remote files already cached, while the file is not re-downloaded, it is copied from the temp folder back to the local storage causing a significant delay:
```r
devtools::install_github("rstudio/pins")
tiny_imagenet <- pins::pin("http://cs231n.stanford.edu/tiny-imagenet-200.zip")
system.time({ tiny_imagenet <- pins::pin("http://cs231n.stanford.edu/tiny-imagenet-200.zip") })
```
```
user  system elapsed 
10.353 102.528 165.082
```
This fix avoid copying anything to the temp folder if the pin is already cached:
```r
devtools::install_github("rstudio/pins", ref = "bugfix/pin-cache-perf")
system.time({ tiny_imagenet <- pins::pin("http://cs231n.stanford.edu/tiny-imagenet-200.zip") })
```
```
user  system elapsed 
6.983   0.889   5.622
```
Note: tiny imagenet is about 250MB, smaller …
> Improve performance for pin() when cache exist for URLs

- DESCRIPTION
- NEWS.md
- R/utils.R
When knitting documents one gets for large files:
This PR disables progress in non-interactive sessions.
> Avoid progress on non-interactive sessions

- DESCRIPTION
- NEWS.md
- R/board_datatxt.R
Fix for https://github.com/rstudio/pins/issues/234
> Properly construct the url when remove cloud pins to fix #234

- DESCRIPTION
- NEWS.md
- R/board_datatxt_headers.R
Fix for `pin()` throwing warning and inconsistent cache state when using custom domain names with `datatxt` boards.
> Support for custom domains in datatxt boards

- DESCRIPTION
- NEWS.md
- R/board_datatxt.R
Reprex here is to create an S3 board, then change the local datatxt with records that don't exist in the remote datatxt, to find out the index is not properly updated.
> Always sync to most up to date datatxt index to fix #239

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_api.R
- vignettes/use-cases.Rmd
Fix for https://github.com/rstudio/pins/issues/245, enables:
```r
library(pins)
board_register(board = "rsconnect", versions = FALSE)
pin(iris, "iris-versioned", board = "rsconnect")
pin_versions("iris-versioned", board = "rsconnect")
```
```
version created               size
<chr>   <chr>                <int>
1 8671    2020-06-15T23:38:15Z 23760
```
Notice that creating a new pin does not create a new version:
```r
pin(iris, "iris-versioned", board = "rsconnect")
pin_versions("iris-versioned", board = "rsconnect")
```
```
version created               size
<chr>   <chr>                <int>
1 8672    2020-06-15T23:38:51Z 23750
```
> Support to disable versions in RStudio Connect

- .travis.yml
- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Admins can override other user content in RStudio Connect boards. This is fine, but `pin()` was defaulting to overriding whichever pin was found by the user. Now we default to the qualified name `user/name` to avoid overriding something unintentionally.
Still, it might be a useful use case for one user to contribute to other user's pin if and only if, the user has permissions to modify such content.
> Avoid overriding pin by admins in rsconnect boards

- R/board_rsconnect.R
Follow up fix to recently developed #245 feature for `versions = FALSE` in rsconnect boarads.
> Proper defaults for rsconnect board and qualified name

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- tests/testthat/test-board-rsconnect.R
Some RStudio Connect servers might be registered to use `http`, but enforce `https`. While this configuration might not be ideal, this fix enables board URLs to handle mismatched protocols.
> Support RStudio Connect servers with mismatched protocols

- tools/process-cran.R
Significant variation on CRAN for Rdata, rData, rdata. Rda, RDA, rda, etc. The current only captures one variation. Enforcing tolower on extension so that the cranfiles generation script can see these. 
Example: #216
> In the wild variation of capitalization

- vignettes/boards-extending.Rmd
Thanks for the great package!
we recently ran into a minor block when trying to implement new board methods and provide those in a new package: the new methods work as a standalone R script but not in the package, because we didn't export the generics in the new package. Although this is a general issue about extending existing s3 methods provided in another package, I thought it would save other people some time if it's in the vignette, so I added a section on exporting s3 generics from pins when new board methods through a new package.
> update vignette for extending boards for using in new R package

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_token.R
When an invalid `account` or `server` parameter are specified in `rsconnect` boards, the following errors are thrown:
```
The server foo is not registered, available servers: beta.rstudioconnect.com 
```
and
```
The account jluraschi is not registered, available accounts: jluraschi, javier
```
> Show proper errors for invalid account and server in rsconnect

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Increase entries retrieved from,
```
> pin_find("", board = "rsconnect")
name                        description                       type  board    
<chr>                       <chr>                             <chr> <chr>    
1 amanda/ticket_attachments   ""                                table rsconnect
2 javier_personal/iris-public ""                                table rsconnect
3 javier_personal/iris-shared ""                                table rsconnect
4 jluraschi/afile11           "A files pin with txt extension." files rsconnect
5 jluraschi/afile141          "A files pin with txt extension." files rsconnect
6 jluraschi/afile144          "A files pin with txt extension." files rsconnect
7 jluraschi/afile164          "A files pin with txt extension." files rsconnect
8 …
```
> Increase entries retrieved in pin_find() for rsconnect to fix #297

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
While we want to avoid admins from overriding a pin by mistake when not specifying the fully qualified name, we still want to allow users to collaborate with pins they co-own.
> Fix regression introduced in #253 to re-enable collaboration and fix #302

- DESCRIPTION
- NEWS.md
- R/board_s3.R
Use HTTPS as suggested in https://github.com/rstudio/pins/issues/304
> Use https by default for s3 boards

- DESCRIPTION
- NEWS.md
- R/board_rsconnect.R
Suppose that a pin is partially created but creation fails before `pin` tag is assigned, in this case, `pin()` won't be able to overwrite the pin since we search for pins but the pin is not yet a pin. Fix is to search all content for the right GUID when the object already exists and validate that we only overwrite content that are pins or are undefined (which should be invalid content anyways).
> Support recreating rsconnect pins partially created

- DESCRIPTION
- NEWS.md
- R/pin_extensions.R
- tests/testthat/test-board-local.R
Adding a test that simulates large files through the codepaths that uses symlinks instead of copying files.
> Add tests for using links in large files

- DESCRIPTION
- NEWS.md
- R/board_rsconnect_bundle.R
- tests/testthat/test-board-dospace.R
10K rows for RSC preview seems to much since some HTML files can grow up to 90MB.
> Adjust row preview from 10k rows to 1K

- .github/workflows/main.yaml
- DESCRIPTION
- NEWS.md
- R/board_s3.R
- tests/testthat/test-board-s3.R
- vignettes/boards-s3.Rmd
Fix for https://github.com/rstudio/pins/issues/304, important since some AWS regions do not longer support V2 signatures.
> Add support for AWS V4 signatures

- DESCRIPTION
- NEWS.md
- R/board_datatxt.R
- R/board_github.R
- R/board_kaggle.R
- R/board_rsconnect_api.R
- R/pin_download.R
It is common to get the following warnings intermittently, so worth assuming the encoding:
```r
> pin_remove("iris", board = "s3path")
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
```
> Silence no encoding warning

- DESCRIPTION
- NEWS.md
- R/board_datatxt.R
- R/board_registration.R
- man/board_register_azure.Rd
- man/board_register_dospace.Rd
- man/board_register_gcloud.Rd
- man/board_register_s3.Rd
Add support for `path` parameter to S3, Azure, Google Cloud and DigitalOceab boards. When `path` is specified, the boards will get created under a sub-directory in the bucket. See https://github.com/rstudio/pins/issues/200
> Add support for 'path' parameter across cloud storage boards

- DESCRIPTION
- NEWS.md
- R/board_rsconnect_bundle.R
Fix for https://github.com/rstudio/pins/issues/190:
```r
tibble::tibble(`With space`=c(1,3)) %>%
pin(name = "pin-with-spaced-col", description = "tibble with column name space", board = "rsconnect")
```
> Preserve column names in RStudio Connect data frame previews

- DESCRIPTION
- NEWS.md
- R/pin_registry.R
Fix for https://github.com/rstudio/pins/issues/270 to avoid searching local boards with an undocumented regular expression.
> Avoid using regexp in pin_find() local boards

- DESCRIPTION
- NEWS.md
- R/board_github.R
Fix for https://github.com/rstudio/pins/issues/285 -- Notice this is only applicable to boards registered with `versions = FALSE`; otherwise, releases are not removed since we want to be able to restore modified and perhaps even deleted pins.
One can question if `pin_remove()` should also remove all versions to match other boards like Kaggle and RStudio Connect; however, that would involve also modifying the repo commit history, which is almost never a good idea.
> Delete tag when deleting or updating a GitHub pin

- vignettes/use-cases/automate-dataset-updates.Rmd
- vignettes/use-cases/create-data-pipelines.Rmd
- vignettes/use-cases/update-plumber-and-shiny-apps.Rmd
There are 3 broken links in the vignettes/examples due to `.htm` endings rather than `.html`. This PR corrects the file ending so that they can link to the correct pieces of content.
> Change .htm to .html in Vignettes

- pkgdown/_pkgdown.yml
before pins 1.0 is available on CRAN it may confuse current connect users that the pins docs and connect docs are out of sync (it confused me).
> build dev site

- NEWS.md
- R/board_local.R
- R/board_rsconnect.R
- R/board_rsconnect_bundle.R
- R/pin-read-write.R
- R/pin-upload-download.R
- man/pin_download.Rd
- tests/testthat/_snaps/board_rsconnect_bundle.md
- tests/testthat/_snaps/pin-upload-download.md
- tests/testthat/test-board_local.R
- tests/testthat/test-board_rsconnect.R
- tests/testthat/test-board_rsconnect_bundle.R
Including discovery that `board_rsconnect()` was inconsistently using `path` metadata key instead of `file`.
Fixes #427
> Ensure that pin_upload()/pin_download() can handle multiple paths

- R/board_rsconnect.R
partial solution to #467
Avoids problems parsing some (development) RSC version strings or (by configuration) unavailable versions.
This does not resolve API compatibility with old RSC releases.
> remove the 1.7.7 version constraint

- R/board_azure.R
- R/board_folder.R
- R/board_rsconnect.R
- R/board_s3.R
- R/board_url.R
- R/cache.R
- R/pin-read-write.R
- R/pin-upload-download.R
- R/testthat.R
- man/pin_download.Rd
- tests/testthat/test-board_url.R
Ensuring that the user can't accidentally modify. Fixes #475
> Mark cached pins as read only

- R/board_rsconnect.R
- R/board_url.R
- man/board_rsconnect.Rd
- man/board_url.Rd
- tests/testthat/test-board_rsconnect.R
I don't see how to test this automatically, but I tested it manually by turning off my wifi and checking that I could connect to a board and download a previously retrieved pin.
Fixes #423
> Allow board_rsconnect() to work offline

- R/board_rsconnect.R
- R/board_rsconnect_server.R
- tests/testthat/_snaps/board_rsconnect_server.md
- tests/testthat/test-board_rsconnect_server.R
Mention manual authorization in `board_rsconnect()`. I don't know if it makes sense to change the function to accept a separate manual option or not. If you think so, I can add something like that. 
Closes #508
> Clarify board_rsconnect allows manual authentication

- R/board_rsconnect.R
- R/board_rsconnect_server.R
- tests/testthat/_snaps/board_rsconnect_server.md
- tests/testthat/test-board_rsconnect_server.R
Since they never actually used envvars, and this now (correctly) fails. And improve auth="envvar" option to give better errors
> Update RSC test boards

- DESCRIPTION
- R/pin-read-write.R
- man/pin_read.Rd
- tests/testthat/_snaps/pin-read-write.md
- tests/testthat/test-pin-read-write.R
- vignettes/pins.Rmd
There are arguments in both [`qsave()`](https://rdrr.io/cran/qs/man/qsave.html) and [`qread()`](https://rdrr.io/cran/qs/man/qread.html) which can affect the performance of reading and writing. Regardless, [qs performs better than RDS](https://github.com/traversc/qs), so I don't think providing a mechanism to change the defaults is needed, at least not initially.
> Add qs format

- .github/workflows/rstudio-connect.yaml
Having a hard time determining that "this PR is coming from a fork"
- `github.repository` is always set to `rstudio/pins`
- `secrets` is not available in the `if` block
> disable rsc workflow if the license is empty

- R/board_rsconnect.R
missing backtick means the badge does not render.
> Missing backtick after the deprecated badge

- R/board_azure.R
Fixes a small typo in board_azure(), 'blob' instead of 'blog' :)
> Fix typo in board_azure()

- DESCRIPTION
- R/board_url.R
- R/legacy_datatxt.R
- README.Rmd
- README.md
- pins-r.Rproj
- tests/testthat/test-board_url.R
- tests/testthat/test-legacy_datatxt.R
- tests/testthat/test-pin.R
- vignettes/pins-update.Rmd
This PR sets up changes needed to change the repo name to "pins-r", for parity with https://github.com/rstudio/pins-python. I tried hard to find everything that would need to be changed, but another set of eyes on this will be great. Also, the changes here will not pass CI until the repo is actually renamed.
> Change repo to "pins-r"

- NEWS.md
- R/board_rsconnect.R
- R/testthat.R
`pins` seems to expect `created_time` with bundles to be in POSIXct format however we're seeing them in POSIXlt format.
RStudio Connect (on Kubernetes):
Version:	2022.05.0
Build:	v2022.05.0-0-g762d29c
This PR fixes it for us, however, we we will most probably want to implement something like this pseudocode:
1. check `created_time`
2. is it POSIXct format?
3. if yes, parse as POSIXct
4. if no, parse as POSIXlt
along with tests. But we'd like to check with you first about the approach before we implement the changes and push to this PR.
> `created_time` for Connect needs to use a different ISO8601 variant

- vignettes/rsc.Rmd
RStudio Connect 1.8.8 introduced the auto-provisioning of CONNECT_API_KEY, but it was not until 1.9.0 that CONNECT_SERVER also become available.
Since not having CONNECT_SERVER specified breaks pins `auth="envvar"`, this PR changes the references to the proper version.
> Fixes a reference to incorrect RSC version

- NEWS.md
- R/pin_reactive.R
Replaces `pin_created()` with `pin_hash()`, which supports functionality of `pin_reactive_read()` and `pin_reactive_download()`.
Suggestion made by @TylerGrantSmith.
Closes #542
> Replacing pin_created with pin_hash

- .github/workflows/R-CMD-check-hard.yaml
- tests/testthat/test-board_rsconnect.R
- tests/testthat/test-board_rsconnect_server.R
- tests/testthat/test-pin-read-write.R
- tests/testthat/test-pin.R
- vignettes/pins-update.Rmd
- vignettes/rsc.Rmd
We already have and probably will be adding more functionality that uses suggested dependencies (such as #644) so let's set ourselves up for success here.
> Add `R-CMD-check-hard`

- DESCRIPTION
- NEWS.md
- R/pin-read-write.R
- tests/testthat/test-pin-read-write.R
Closes #644.
Note: writing to arrow was previously returning the object (invisibly), rather than the fully qualified path (invisibly) like the help says. It now returns the path. As far as I can tell, no tests check this. I think json and csv likely return the object, but I haven't dug in to confirm.
> Move arrow to suggests.

- NEWS.md
- R/board_rsconnect.R
- R/board_rsconnect_bundle.R
Addresses #636 
This change address the problem of ending up with pin names like `julia.silge/julia.silge/mtcars`:
``` r
library(pins)
b <- board_rsconnect()
#> Connecting to RSC 2022.07.0 at <https://colorado.rstudio.com/rsc>
pin_write(b, mtcars, "mtcars-01")
#> Writing to pin 'julia.silge/mtcars-01'
pin_write(b, mtcars, "julia.silge/mtcars-01")
#> Writing to pin 'julia.silge/mtcars-01'
pin_write(b, mtcars, "julia.silge/mtcars-02")
#> Writing to pin 'julia.silge/mtcars-02'
```
<sup>Created on 2022-08-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Update how user names are handled in Connect preview, message, error

- NEWS.md
- R/meta.R
- tests/testthat/_snaps/board_rsconnect_bundle.md
- The `parse_8601_compact` function seems to be dropping the seconds from a timestamp. Adding the `%S` part of the format string preserves them. This might fix issue #637  - at least ensuring that files written within > 1s receive a unique version number.
> Added %S to the datetime format string to avoid loss of precision

- NEWS.md
- R/board_s3.R
- man/board_s3.Rd
Closes #628 
``` r
library(pins)
b <- board_s3(
"pins-test-hadley", 
region = "us-east-2",
access_key = Sys.getenv("PINS_AWS_ACCESS_KEY"),
secret_access_key = Sys.getenv("PINS_AWS_SECRET_ACCESS_KEY")
)
b %>% pin_write(mtcars, Tagging = "key1=value1&key2=value2")
#> Using `name = 'mtcars'`
#> Creating new version '20220831T215459Z-66143'
#> Writing to pin 'mtcars'
```
<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Pass the dots from `pin_write()` through to `s3_upload_file()`

- NEWS.md
- R/board_s3.R
Fixes issue discussed in https://github.com/rstudio/pins-r/issues/625#issuecomment-1242558838
> add ... to s3_upload_yaml to fix issue noted in #625

- NEWS.md
- R/pin_versions.R
- tests/testthat/_snaps/pin_versions.md
- tests/testthat/test-pin_versions.R
Closes #656 
``` r
library(pins)
tmp <- tempdir()
board <- board_folder(tmp, versioned = TRUE)
pin_write(board, mtcars, 'my-beautiful-cars')
#> Creating new version '20220930T035916Z-66143'
#> Writing to pin 'my-beautiful-cars'
pin_versions(board)
#> Error in `pin_versions()`:
#> ! Argument `name` is missing, with no default
#> Backtrace:
#>     ▆
#>  1. └─pins::pin_versions(board)
#>  2.   └─rlang::abort("Argument `name` is missing, with no default") at pins-r/R/pin_versions.R:42:4
pin_versions(board, 'my-beautiful-cars')
#> # A tibble: 1 × 3
#>   version                created             hash 
#>   <chr>                  <dttm>              <chr>
#> 1 20220930T035916Z-66143 2022-09-29 21:59:16 66143
```
<sup>Created on 2022-09-29 with [reprex …
> Add a better error for `pin_versions()`

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- tests/testthat/test-board_url.R
Related to #650 
This particular test only checks putting the whole path including the version into the URL for `board_url()`, but let's get this piece reviewed and merged so we have a good strategy for testing this kind of process.
> Add test for writing with `board_folder()` ➡️ reading with `board_url()`

- NEWS.md
- R/pin-read-write.R
Closes #626 
Setting `stringsAsFactors = TRUE` seems quite unexpected now, especially 2+ years after this default changed in base R. It results in behavior that surprises many (I would guess most) users, for example see #596.
> No more `stringsAsFactors`

- NEWS.md
- R/board_rsconnect.R
- R/board_url.R
- tests/testthat/_snaps/board_rsconnect.md
Addresses #635 
Instead of removing these troublesome caches like #660 was headed for, this PR instead changes these caches over to use environments (instead of files on disk). This means that:
- caches will not persist between sessions
- caches will only get into a broken state if a big change is made with the server while a user is working with pins from R
- caches can be fixed by restarting R
- the first time functions are called they will be slow, but subsequent calls will have the same benefits of caching as we have now
> Use environments for Connect content + user caches

- R/board_azure.R
- R/board_ms365.R
- R/board_s3.R
- man/board_azure.Rd
- man/board_ms365.Rd
- man/board_s3.Rd
Related to #673 
I did not add this to `board_rsconnect()` because the needed packages are always there.
I looked into how to do this with less repetition via `@includeRmd` or other templating, but you have to have the board to call `required_pkgs()` and we don't have all the boards when building the docs or on CRAN.
> Add docs for automatic dependency discovery

- NEWS.md
- R/board_rsconnect.R
- inst/preview/index.html
- tests/testthat/_snaps/board_rsconnect.md
- tests/testthat/_snaps/board_rsconnect_bundle.md
Closes #615 
For now, let's not try to show code for both R and Python for each pin; that would require us at the least to check the type of pin to see if it is readable. This PR:
- updates the preview so it says "R Code" ([see an example](https://colorado.posit.co/rsc/content/760d199d-50da-4c7b-ac45-c829263112f1/))
- updates the `deparse` method so it follows the [current Connect docs](https://docs.posit.co/connect/user/pins/)
> Update Connect preview

- vignettes/pins-update.Rmd
This PR updates the [vignette](https://pins.rstudio.com/articles/pins-update.html) we have that compares to the older version of this package, adding in:
- the new `board_gcs()`
- advice on using `board_folder()` plus `board_url()` instead of the older GitHub board
> Upgrade the "Upgrading to pins 1.0.0" vignette

- R/board.R
- R/board_folder.R
- tests/testthat/test-board_folder.R
Closes #714 
This PR removes calling `pin_list()` when you print out a board (too slow) and refactors the `print` method to take advantage of [cli](https://cli.r-lib.org/) functions.
> Refactor `print` method for boards

- R/board_connect.R
- tests/testthat/test-board_connect.R
Closes #680 
This PR adds a new test that we can:
- Write a pin as one Connect user
- Add a different Connect user as owner (new little testing function to do this)
- New owner can write to the pin
> Add test for writing to another user's pin

- NEWS.md
- R/board_s3.R
Pagination implementation for S3 board of the `pin_list.pins_board_s3` & `pin_versions.pins_board_s3`.
> S3 pagination implementation

- vignettes/customize-pins-metadata.Rmd
- vignettes/managing-custom-formats.Rmd
Closes #456 
This PR adds a new section to the ["Managing custom formats"](https://pins.rstudio.com/articles/managing-custom-formats.html) vignette about how to wrap `pin_write()` / `pin_read()` for consistent metadata.
> Update vignette for how to customize metadata for specific use case

- NEWS.md
- R/pin-read-write.R
- README.Rmd
- README.md
- man/pin_read.Rd
- tests/testthat/_snaps/pin-read-write.md
- tests/testthat/test-pin-read-write.R
- vignettes/pins.Rmd
Closes #713 
``` r
library(pins)
b <- board_temp()
b %>% pin_write(palmerpenguins::penguins, "penguins-have-factors", type = "parquet")
#> Creating new version '20230306T164332Z-cdfce'
#> Writing to pin 'penguins-have-factors'
b %>% pin_read("penguins-have-factors")
#> # A tibble: 344 × 8
#>    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
#>    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
#>  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
#>  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
#>  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
#>  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
#>  5 …
```
> Add `type = "parquet"`

- NEWS.md
- R/pin-meta.R
- R/pin-read-write.R
- R/testthat.R
- R/utils.R
- man/pin_read.Rd
- tests/testthat/_snaps/board_folder.md
- tests/testthat/_snaps/pin_versions.md
- tests/testthat/test-board_connect.R
- tests/testthat/test-board_folder.R
- tests/testthat/test-pin_versions.R
Addresses #589 
This does not solve all our hashing issues (for example, the `pin_hash` still only looks at the pin _contents_ and not the metadata) but it is a small step toward a better hashing situation.
After talking with users, I think that an opt-in new argument is the best way forward (rather than, say, a new function or new default behavior). This new `check_hash` arg comes after the dots and defaults to `FALSE`. It does require another read of `pin_meta()` to get the old hash.
``` r
library(pins)
b <- board_temp(versioned = TRUE)
b %>% pin_write(1:10, "nice-numbers", check_hash = TRUE)
#> Creating new version '20230426T224520Z-7f884'
#> Writing to pin 'nice-numbers'
Sys.sleep(2)
b %>% pin_write(1:10, "nice-numbers", check_hash = TRUE)
#> Guessing `type …
```
> New `force_identical_write` arg

- R/meta.R
- R/pin-meta.R
- tests/testthat/_snaps/meta.md
Closes #612 
This PR makes the API version (currently, possible values are 0 and 1, or it can be absent for old pins) stored in the metadata more consistent, i.e. stored and read as int.
The error message is intended to communicate about the package version (e.g. 1.1.0.9000 right now) to the user. The API stored in the metadata is more like an internal value and the package version is more like an external value. If we ever drastically changed the user-facing API again, we would bump the package version to 2.0.0, `api_version` to 2, and go from there.
> Make API version in metadata more consistent

- R/testthat.R
- tests/testthat/_snaps/pin.md
- tests/testthat/setup.R
- tests/testthat/test-pin.R
This PR only switches over the old `pin()` tests, but when `/cache` and `/etag` are added as outlined in r-lib/webfakes#3 then I can switch over the `board_url()` tests.
> Switch to webfakes httpbin

- R/board_connect.R
I think what was being hashed here before was `base::url()` 🙈
> Fix hashing for Connect URL in cache

- R/pin-meta.R
The problems with testing on the cloud boards have been making my feel like I am LOSING MY MIND, but maybe it is related to this.
> Use `force_identical_write` to update metadata in test

- NEWS.md
- tests/testthat/test-pin-read-write.R
Closes #761 
This PR changes the read 🔄 write tests to use `tibble::tibble()` to account for the new behavior in arrow, which now always returns a tibble on reading. If you write a tibble, only the CSV storage option now returns a `data.frame`. I went back and forth on how to handle this change, but I now think the best thing to do is to keep the same behavior in pins that arrow has.
This PR works with both old and new arrow, so we could do a release whenever. I tested locally with the devel version of arrow.
> Update test for new arrow release

- NEWS.md
- R/pin-read-write.R
Closes #760 
This PR moves the ellipsis checking to _after_ the early return when we don't write. The messaging now looks like this:
``` r
library(pins)
b <- board_connect()
#> Connecting to Posit Connect 2023.07.0 at <https://colorado.posit.co/rsc>
b |> pin_write(
1:10, 
"julia.silge/some-amazing-numbers",
access_type = "all"
)
#> ! The hash of pin "julia.silge/some-amazing-numbers" has not changed.
#> • Your pin will not be stored.
```
<sup>Created on 2023-08-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Move ellipsis checking

- NEWS.md
- R/board_gdrive.R
This is a potential fix to #777 
Instead of passing a full path to `drive_upload`, with this pr we first create a dribble with the destination folder, and then use it as a path. 
In my computer, it works with a single or multiple files, uploading to the main google drive folder or to  folder with a long path.
For example, now this works without any issues:
```
drive_link = "https://drive.google.com/drive/folders/1_jiG0VtENy5QcLRziN7DM_zQD4egwGuN"
googledrive::drive_auth(email = "myemail@gmail.com")
gdrive_board = pins::board_gdrive(drive_link)
gdrive_board |> pins::pin_upload(paths = "~/Downloads/999.zip", name = "Id_pin")
```
> Use a dribble to define the upload destination path

- NEWS.md
- R/board_gdrive.R
Closes #781 
When I first put together the support for the Google Drive board, I did not pay enough attention to what is guaranteed to come in a dribble object:
https://googledrive.tidyverse.org/reference/dribble.html
This PR addresses this more holistically than #780, throughout all the methods. I don't think I want to change my general testing strategy, but I did just locally run through this (after running `devtools::load_all()`):
```r
my_dribble <- googledrive::as_dribble("https://drive.google.com/drive/u/1/folders/1GQ-JuG4pT1AK9VLz9UZptnO73H7zDaUe")
board <- board_gdrive(my_dribble)
test_api_basic(board)
test_api_versioning(board)
test_api_meta(board)
```
All these tests pass and I expect this to now work much better.
> Fix how `board_gdrive()` uses dribble components

- R/board_connect.R
Closes #786
See discussion https://github.com/posit-conf-2023/vetiver/discussions/31
> Add "write" to warning about using full name when referencing pin

- NEWS.md
- R/pin-read-write.R
- man/pin_read.Rd
- tests/testthat/_snaps/pin-read-write.md
- tests/testthat/test-pin-read-write.R
We've been talking about `...` being in the wrong place for quite a while, and we think it's time to rip the band-aid off for a better experience for people. 
Technically we "should" put the dots _before_ `name` but it is very very very common for folks to provide `name` by position (without `name = `). We do it in all our docs and tests, and I believe it is very common with users as well. I would like to propose that we move the dots to between `name` and `type`, as it will not be too disruptive for users and we'll be able to get to our better situation of moving around or adding args after the dots.
The new error that folks see if they are passing by position is this:
``` r
library(pins)
board <- board_temp()
board |> pin_write(10:20, "nice-numbers", "json", "my great title")
#> Error …
```
> Change the `pin_write()` function signature, moving the dots

- NEWS.md
- R/board_connect.R
- man/board_connect.Rd
- tests/testthat/_snaps/board_connect.md
In #667 we moved from caches saved to disk to environment caches, but this still causes problems that are very confusing and hard to reason about, as @ryjohnson09 demonstrates in #789. I would like to propose we just throw this whole idea away; my opinion is that these Connect user and content caches are not gaining us much (especially now that they are only environment caches) and when things go wrong, it's pretty horrible.
> Finally rip out these Connect user and content caches

- NEWS.md
- R/board_connect_bundle.R
- R/meta.R
- R/pin-meta.R
- R/pin-read-write.R
- inst/preview/index.html
- man/pin_meta.Rd
- man/pin_read.Rd
- tests/testthat/_snaps/board_azure_adls2.md
- tests/testthat/_snaps/board_azure_blob.md
- tests/testthat/_snaps/board_azure_file.md
- tests/testthat/_snaps/board_connect.md
- tests/testthat/_snaps/board_connect_bundle.md
- tests/testthat/_snaps/board_folder.md
- tests/testthat/_snaps/board_gcs.md
- tests/testthat/_snaps/board_gdrive.md
- tests/testthat/_snaps/board_s3.md
- tests/testthat/_snaps/meta.md
- tests/testthat/_snaps/pin-read-write.md
- tests/testthat/test-board_connect_bundle.R
- tests/testthat/test-pin-read-write.R
One thing we thought about when listening to JD Long's keynote talk at posit::conf last month was the value of making sure it is as easy as possible connect datasets to documentation. This PR is inspired by those thoughts and adds a new option for storing `urls` (a character vector) along with your dataset.
It's used like this:
``` r
library(pins)
b <- board_connect()
#> Connecting to Posit Connect 2023.07.0 at <https://colorado.posit.co/rsc>
b |> pin_write(
c(200, 404, 503),
"http-code-numbers",
urls = c("https://httbey.com/", "https://http.cat/"),
force_identical_write = TRUE
)
#> Writing to pin 'julia.silge/http-code-numbers'
```
<sup>Created on 2023-10-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
I added the URLs to the Connect preview, which …
> Add new `urls` to metadata

- NEWS.md
- R/board_connect_bundle.R
- inst/preview/index.html
- tests/testthat/_snaps/board_connect_bundle.md
- tests/testthat/test-board_connect_bundle.R
Addresses #796
We discussed a button to switch between the R / Python code, but we need to _not_ show the code at all for `.rds` pins so I think it's better to just do it with another `<section>`. This is my current proposal:
You can see a [published version here](https://colorado.posit.co/rsc/content/a444e2ba-1d26-4945-99ce-7d184a82385d).
> Add Python code to Connect preview HTML

- R/board_connect_url.R
- R/pin-read-write.R
- man/board_connect_url.Rd
- tests/testthat/_snaps/board_url.md
- tests/testthat/_snaps/pin-read-write.md
Closes #810 
We now see a message like this when we end up in a bad URL situation, such as trying `pin_read()` on a full path or forgetting a trailing slash for a vanity URL:
``` r
library(pins)
board <- board_connect_url(c(
numbers = "https://colorado.posit.co/rsc/some-nice-numbers"
))
board |> pin_read("numbers")
#> Error in `object_read()`:
#> ! Cannot automatically read pin:
#> • Is your pin specified as a full path? Retrieve it with `pin_download()`
#> • Is your pin specified via a URL that is not a full path, such as a Posit
#>   Connect vanity URL? Remember to include a trailing slash `/`
#> Backtrace:
#>     ▆
#>  1. └─pins::pin_read(board, "numbers")
#>  2.   └─pins:::object_read(meta)
#>  3.     └─cli::cli_abort(...)
#>  4.       └─rlang::abort(...)
```
<sup>Created on …
> Improve error message for problems with URLs

- R/board_connect.R
- man/board_connect.Rd
> Clarify authentication for Connect

- README.Rmd
- vignettes/pins.Rmd
Based on feedback during a recent pins stakeholder meeting, let's further clarify what and how to write objects/data as pins.
If we think this language is good to go, I will do a PR to pins for Python as well as the Connect docs.
> Update docs, especially about concurrent writes

- NEWS.md
- R/board_gdrive.R
Closes #818.
This PR changes to use `drive_id` instead of folder `name` when creating folders in gdrive.
This change resolves the issue of creating folders due to duplicate folder names.
This change resolves #818 locally.
``` r
library(pins)
library(googledrive)
drive_auth("uchidamizuki@vivaldi.net")
board <- board_gdrive(as_id("11wUPQi82qsXArmMeu3ENdUK_QvdU1rMv"))
board |> 
pin_write(iris, "iris")
#> Creating new version '20240111T113330Z-d16b7'
#> Writing to pin 'iris'
```
<sup>Created on 2024-01-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
> Fix folder creation by `gdrive_mkdir()`

- DESCRIPTION
- R/board.R
- R/board_azure.R
- R/board_connect.R
- R/board_gcs.R
- R/board_gdrive.R
- R/board_ms365.R
- R/board_s3.R
- R/pin-delete.R
- R/pin-read-write.R
- R/pin-store-fetch.R
- R/pin_exists.R
- R/pin_list.R
- R/pin_search.R
- R/pin_versions.R
- R/required_pkgs.R
Since deprecated in version 1.0. https://rlang.r-lib.org/news/index.html#argument-intake-1-0-0
ellipsis imports rlang anyway
> Remove ellipsis dependency in favour of rlang

- .github/workflows/lock.yaml
- .github/workflows/posit-connect.yaml
- tests/testthat/test-board_url.R
There are two changes here:
- Updating the lock GH action to use a more recent version which hopefully won't fail so much
- Skipping the webfakes tests on the test coverage action, since it currently fails
> Some maintenance on GH actions

- R/board_connect.R
- tests/testthat/test-board_connect-mocks.R
With a Connect board, pins can (and should) be specified with `owner/name`, as the pin `name` is unique per user account. This PR fixes a bug that occurs when multiple pins have the same `name` and the `owner` is not the first match.
To retrieve content from Connect:
1. We parse the `name` into a list with `owner` and `name` fields, e.g. `"toph/penguins"` becomes `list(owner = "toph", name = "penguins", full = "toph/penguins)"`.
2. We get a list of all content with matching names. For example, we might get a list of two items, the first representing `"taylor_steinberg/penguins"`, the second `"toph/penguins"`.
3. If there is more than one item, `owner` must have been specified, so we can filter the list. Because the JSON returned from the API only contains owner GUIDs, we use the Connect …
> Fix how multiple pin name matches from a Connect board are filtered

- NEWS.md
- R/pin_versions.R
Fixes #837.
Here is a reprex of the fix:
``` r
library(pins)
write.csv(mtcars, file = "mtcars.csv")
board <- board_temp(versioned = TRUE)
pin_upload(board = board, paths = "mtcars.csv", name = "data")
#> Creating new version '20240827T112516Z-cd94d'
pin_versions(board, "data")
#> # A tibble: 1 × 3
#>   version                created             hash 
#>   <chr>                  <dttm>              <chr>
#> 1 20240827T112516Z-cd94d 2024-08-27 13:25:16 cd94d
latest_version <- pin_versions(board = board, name = "data")$version
pin_version_delete(board = board, name = "data", version = latest_version)
pin_versions(board, "data")
#> # A tibble: 0 × 3
#> # ℹ 3 variables: version <chr>, created <dttm>, hash <chr>
pin_upload(board = board, paths = "mtcars.csv", name = "data")
#> Creating new …
```
> Fixed edge case where n_versions = 0

- DESCRIPTION
- NEWS.md
- R/pin-read-write.R
- tests/testthat/test-pin-read-write.R
- vignettes/pins.Rmd
> Use nanoparquet package, to read/write parquet files

- NEWS.md
- R/board_connect.R
- R/board_connect_bundle.R
- man/board_connect.Rd
- tests/testthat/_snaps/board_connect_bundle.md
- tests/testthat/test-board_connect_bundle.R
Closes #849
You can turn off the little preview table with this change, by doing:
```r
library(pins)
b <- board_connect()
b  |> pin_write(mtcars, type = "parquet", preview_data = FALSE)
```
This works similarly to the Connect-only `access_type` argument; both appear _after_ the dots in the `pin_store` method.
> Add new argument to turn off data preview (table) on Connect

- NEWS.md
- R/pin-upload-download.R
Closes #847 
We don't need to use `check_pin_name()` in this function, because it is called in a board-specific way in each board's `pin_store` method.
> Do not `check_pin_name()` in `pin_upload()`

- NEWS.md
- R/board_s3.R
- man/board_s3.Rd
Closes #851 with some hopefully more helpful documentation for people using S3-compatible object storage on platforms other than AWS
> Improve `board_s3()` docs for non-AWS S3-compatible storage

- NEWS.md
- R/board_connect.R
- R/board_connect_server.R
> rsconnect::accounts returns a zero-length data.frame and previously returned NULL

- DESCRIPTION
- NEWS.md
- R/board_connect_bundle.R
- R/pin-read-write.R
- man/pin_read.Rd
- tests/testthat/_snaps/pin-read-write.md
- tests/testthat/test-pin-read-write.R
- vignettes/pins.Rmd
Hey,
This PR introduces the `qs2` format, the successor to the `qs`, as proposed in #865. In a nutshell, it adds:
* a new family of functions, `read_qs2()` and `write_qs2()`
* updated documentation and tests
* a deprecation warning for the `qs` format.
I am unsure about the latter, as the lifecycle of the `qs` package is unclear to me. However, it will certainly be deprecated in the foreseeable future; the only unknown is when. See https://github.com/qsbase/qs/issues/103
> Add support of the `qs2` format

- vignettes/pins.Rmd
Before (currently wrong at https://pins.rstudio.com/articles/pins.html#metadata):
After:
> Force identical write
