NEWS.md
R/board_rsconnect_bundle.R
inst/views/data/pagedtable-1.1/pagedtable.css
inst/views/data/pagedtable-1.1/pagedtable.js

https://beta.rstudioconnect.com/connect/#/apps/6565/access

Fix paged tables with long text and special characters

---

DESCRIPTION
NEWS.md
R/pin_download.R
R/pin_extract.R

Support for,
```r
pins::pin("http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2019-09-14/data/listings.csv.gz", "ams_airbnb")
```

Support to extend extractions and gzip support

---

R/pin_download.R
R/pin_extensions.R
R/utils.R

Two follow up fixes required for yesterday changes.

Follow up fixes to progress and gzip

---

R/pin.R

small typo

---

DESCRIPTION
NEWS.md
R/board_datatxt.R
R/board_github.R
R/board_kaggle.R
R/board_local.R
R/board_packages.R
R/board_rsconnect.R
R/pin.R
R/pin_download.R
R/pin_extensions.R
R/pin_reactive.R
man/pin_get.Rd
man/pin_reactive.Rd

Fix,
```r
pins::pin_get("davidkyle/got-subtitles", board = "kaggle") %>%
readr::read_csv(col_types = readr::cols())
```

Fix kaggle board with proper zip extraction

---

R/board_registration.R
R/board_test.R

fix board_register_azure()

---

DESCRIPTION
R/board_datatxt.R

Related to https://github.com/rstudio/pins/pull/102, also need to handle paths of files in addition to directories with data.txt.

Fix artifact paths for datatxt board

---

R/board_datatxt.R

Fix for https://github.com/rstudio/pins/issues/109 to allow retrieving pins even in high-concurrency scenarios when using cloud boards.

Fallback to retrieve by path when pins not in index to fix #109

---

.travis.yml
NEWS.md
R/pin.R
R/pin_dataframe.R
R/pin_default.R
R/pin_files.R
R/pin_package.R
tests/testthat/test-pin-datatable.R
tests/testthat/test-pin-identity.R

Fix for https://github.com/rstudio/pins/issues/124

Avoid casting data.tables to tibbles

---

NEWS.md
R/board.R
R/board_datatxt.R
R/board_github.R
R/board_kaggle.R
R/board_manifest.R
R/board_registration.R
R/board_rsconnect.R
R/board_test.R
R/pin.R
R/pin_download.R
R/utils.R
inst/rstudio/shinyaddin/www/addin.css
inst/rstudio/shinycon/app.R
man/board_register_datatxt.Rd
tests/testthat/test-board-datatxt.R

Split the fixes from [blog post branch](https://github.com/rstudio/pins/pull/123) to allow us to test this release.

Fixes for pins 0.3.0 blog post

---

NEWS.md
R/board_datatxt.R
R/board_local.R
R/pin.R
R/pin_manifest.R
R/pin_registry.R

Fix for https://github.com/rstudio/pins/issues/138.

Properly remove files from website boards to fix #138

---

NEWS.md
R/pin.R

```r
pin(iris)
pin_info("iris")
```
```
```

Minor improvement to pin_info() for paths

---

DESCRIPTION
NEWS.md
R/board_github.R
R/board_test.R

Fix for https://github.com/rstudio/pins/issues/168 which prevents users from uploading large files to GitHub, planning to push this as a patch to CRAN.

Fix regression uploading large datasets to GitHub

---

DESCRIPTION
NEWS.md
R/pin_extensions.R

Refresh connection pane on pin()

---

DESCRIPTION
NEWS.md
R/board_rsconnect.R

Fix for https://github.com/rstudio/pins/issues/195

Properly support port numbers in rsconnect board to fix #195

---

DESCRIPTION
NEWS.md
R/board_github.R
tests/testthat/test-board-github.R

Avoid multiple GitHub commits to fix https://github.com/rstudio/pins/issues/197.

Commit all GitHub files with a single commit

---

DESCRIPTION
NEWS.md
R/board_kaggle.R
R/pin_download.R
vignettes/boards-kaggle.Rmd

Fixes https://github.com/rstudio/pins/issues/24
```r
pin_find("crowdflower", board = "kaggle")
```
```
name                                                    description                                     type  board 
<chr>                                                   <chr>                                           <chr> <chr> 
1 awsaf49/ecommerce-search-result-relevane-by-crowdflower eCommerce Search Result Relevane by Crowdflower files kaggle
2 c/crowdflower-search-relevance                          Crowdflower Search Results Relevance            files kaggle
3 c/crowdflower-weather-twitter                           Partly Sunny with a Chance of Hashtags          files kaggle
4 crowdflower/first-gop-debate-twitter-sentiment          First GOP Debate Twitter Sentiment …
```

Support to find and download data from Kaggle competitions

---

DESCRIPTION
NEWS.md
R/board_rsconnect_token.R

Fix for https://github.com/rstudio/pins/issues/256

Support for redirect servers in rsconnect boards

---

R/board_datatxt.R

Fix for https://github.com/rstudio/pins/issues/259

Allow datatxt boards to retain caches to fix #259

---

DESCRIPTION
NEWS.md
R/board_rsconnect_token.R

Fix for https://github.com/rstudio/pins/issues/261

throw error when multiple acccounts associated to same rsconnect server to fix #261

---

DESCRIPTION
NEWS.md
R/pin_extensions.R
man/custom-pins.Rd

Fix for https://github.com/rstudio/pins/issues/273

Use symlinks to avoid copying large files

---

DESCRIPTION
NEWS.md
R/board_datatxt.R
R/board_gcloud.R
derby.log
logs/log4j.spark.log

Fix for https://github.com/rstudio/pins/issues/275

Disable Google Cloud index cache

---

DESCRIPTION
NEWS.md
R/pin_extensions.R

Fix for https://github.com/rstudio/pins/issues/277

Avoid local paths with pin(zip = TRUE)

---

DESCRIPTION
NEWS.md
R/ui_viewer.R

Fix for https://github.com/rstudio/pins/issues/280

Prevent connections pane from hanging to fix #280

---

R/board_rsconnect_bundle.R

Port for https://github.com/rstudio/rsconnect/pull/447/files

Use rsconnect tar if available

---

R/board_rsconnect.R

Just porting fix from https://github.com/rstudio/pins/pull/306/

Port fix for rstudio/pins/pull/306

---

DESCRIPTION
NEWS.md
R/pin_extensions.R

Follow up to https://github.com/rstudio/pins/pull/311

Support downloading files when incompatible data.txt exists

---

pkgdown/_pkgdown.yml
vignettes/advanced-too-big.Rmd

I wasn't sure if I needed to build the pkgdown docs locally and commit the HTML or if that happened automatically. Let me know if I need to do so. 
I'd also appreciate a good once over on the recommendations!

add article cautioning against pinning big data

---

DESCRIPTION
NEWS.md
R/pin_extensions.R

Fix for https://github.com/rstudio/pins/issues/127

Workaround to yaml encoding windows crashes

---

DESCRIPTION
NEWS.md
R/board_datatxt.R

Prevent creating pins with unsupported characters to fix https://github.com/rstudio/pins/issues/193

Avoid pins with unsupported characters in cloud boards

---

DESCRIPTION
NEWS.md
R/board_github.R

Fix for https://github.com/rstudio/pins/issues/199

Properly store relative paths in GitHub boards

---

DESCRIPTION
NEWS.md
R/board_github.R
R/board_registration.R

New repos are being created with `main` branch, this PR supports them and fixes https://github.com/rstudio/pins/issues/336

Add support for repos with main branch

---

DESCRIPTION
NEWS.md
R/board_github.R
R/pin_download.R
R/pin_manifest.R

Fix for https://github.com/rstudio/pins/issues/292

Support for releases in private GitHub repos

---

vignettes/boards-extending.Rmd

Fix for https://github.com/rstudio/pins/issues/309

Improve board extensions docs

---

NEWS.md
R/board_rsconnect_token.R

FIx for https://github.com/rstudio/pins/issues/327

Improve rsconnect error when authentication fails

---

R/pin.R
vignettes/advanced-too-big.Rmd

Fix for https://github.com/rstudio/pins/issues/325

Document as-is pin in function and vignette

---

README.Rmd
README.md
_pkgdown.yml
vignettes/pins-legacy.Rmd

Add vignette about legacy api

---

R/cache.R
R/testthat.R

Test that caches are touched

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/rstudio-connect.yaml
.github/workflows/test-coverage.yaml

@colearendt you might like to know about the new setup-r-dependencies action 😄

Update actions to latest workflows

---

DESCRIPTION
R/board_s3.R
man/board_s3.Rd
tests/testthat/test-board_s3.R

Add prefix argument to board_s3()

---

R/board_azure.R

compute Azure storage hash using container URL

---

R/board_kaggle.R
R/board_rsconnect.R
R/pin_search.R
man/board_kaggle.Rd
man/pin_search.Rd
tests/testthat/test-pin_search.R

Make it clear that you can search for all pins

---

R/board_folder.R

Fixes #510
@hongooi73 can you please see if this helps?

Normalize path

---

R/board_rsconnect_server.R
tests/testthat/_snaps/board_rsconnect_server.md

Make error more helpful if rsconnect package not installed

---

.github/workflows/rstudio-connect.yaml
.gitignore
DESCRIPTION
R/board.R
R/board_kaggle.R
R/board_rsconnect.R
man/board_rsconnect.Rd
man/board_s3.Rd
man/new_board.Rd
man/pins-package.Rd
tests/testthat/_snaps/board_folder.md
tests/testthat/_snaps/board_rsconnect.md
tests/testthat/_snaps/board_rsconnect_server.md
tests/testthat/_snaps/board_url.md
tests/testthat/_snaps/legacy_board.md
tests/testthat/_snaps/legacy_packages.md
tests/testthat/_snaps/legacy_registry.md
tests/testthat/_snaps/pin-delete.md
tests/testthat/_snaps/pin-meta.md
tests/testthat/_snaps/pin-read-write.md
tests/testthat/_snaps/pin-upload-download.md
tests/testthat/_snaps/pin.md
tests/testthat/_snaps/pin_info.md
tests/testthat/_snaps/pin_search.md
tests/testthat/_snaps/pin_versions.md
tests/testthat/test-board_rsconnect.R

TODO: list out the env vars we need to run all tests

Refresh actions + tests

---

.github/workflows/R-CMD-check.yaml
tests/testthat/test-legacy_packages.R

Add more older R versions to R CMD check

---

NEWS.md
vignettes/managing-custom-formats.Rmd

fix #631
Hi again,
Sorry I got pulled away on some other things...
I propose a short vignette, as it seemed a bit long for function documentation - happy to modify as you see fit!
Thanks!

add documentation for custom formats

---

R/board_s3.R
man/board_s3.Rd

Document that pins doesn't create a new S3 bucket

---

R/board_kaggle.R

Looks like Kaggle now returns a 403 here

Update `board_kaggle()` for new behavior

---

R/board_rsconnect.R

This file had a lot of styling that doesn't play nicely with RStudio defaults.

Restyle `board_rsconnect()` file

---

.github/workflows/check-boards.yaml
R/board_azure.R
tests/testthat/_snaps/board_azure_adls2.md
tests/testthat/_snaps/board_azure_blob.md
tests/testthat/_snaps/board_azure_file.md

Closes #580 
Why didn't these snapshot updates show up as needed in #671? 🤔

Update Azure infrastructure

---

R/board_s3.R
man/board_s3.Rd

Closes #663 
@tomasjanikds do you mind checking this out and seeing if it would have helped you when you were trying to get this to work?

Add docs for MinIO storage

---

DESCRIPTION
vignettes/managing-custom-formats.Rmd

Add example for how to compress/archive/pin whole directory to new vignette

---

R/board_rsconnect.R

The demo server [has moved](https://colorado.posit.co/rsc/).

Update to new colorado server URL

---

R/pin-read-write.R
man/board_url.Rd
man/pin_read.Rd

Closes #687 
Just a little reminder to help folks understand how their data is being stored

Document which `types` are plain text vs binary

---

R/board_url.R
tests/testthat/test-board_url.R

fix small typo

---

DESCRIPTION
NEWS.md
R/board_azure.R
R/board_gcs.R
R/board_ms365.R
R/board_s3.R
README.md
cran-comments.md
man/board_azure.Rd
man/board_gcs.Rd
man/board_ms365.Rd
man/board_s3.Rd
revdep/cran.md
vignettes/posit-connect.Rmd

Release candidate v1.1.0

---

R/board_azure.R
R/board_ms365.R
R/board_s3.R
man/board_azure.Rd
man/board_ms365.Rd
man/board_s3.Rd

Related to #703 
Thank you again @jennybc!

Fix quotes in `requireNamespace()`

---

R/board_connect.R
man/board_connect.Rd

More clearly document what `use_cache_on_failure` does with Connect

---

.github/rstudio-connect.gcfg
.github/workflows/posit-connect.yaml

Simplify testing setup for Connect

---

_pkgdown.yml

Based on info from Andrew Williams

Add Google Tag Manager

---

.github/cross-compat/read-pins.R
.github/cross-compat/read-pins.py
.github/cross-compat/write-pins.R
.github/cross-compat/write-pins.py
.github/workflows/cross-compat.yml

Add R 🔁 Python cross compatibility tests

---

DESCRIPTION
tests/testthat/test-board_url.R

Use webfakes for `board_url()` tests

---

R/board_gdrive.R
R/pin-meta.R

Somehow I was totally unaware of [this](https://purrr.tidyverse.org/reference/faq-adverbs-export.html), despite it being linked from the `possibly()` docs.

Fix uses of `possibly()`

---

DESCRIPTION
NEWS.md
README.md
cran-comments.md
revdep/cran.md
vignettes/pins-update.Rmd

Release candidate v1.2.1

---

DESCRIPTION
NEWS.md
R/legacy_azure.R
cran-comments.md
man/legacy_azure.Rd
man/pins-package.Rd
revdep/README.md
revdep/cran.md
vignettes/pins.Rmd

Release candidate 1.4.0

---

.github/workflows/check-boards.yaml

Test the S3 bucket auth in CI
